### ISSUE TITLE
Demo content request

### ISSUE THREAD

**Issue by traumturbulenzen** [pmoreno-rodriguez/grav-theme-future2021#1]
Hello out there,
I hope this finds you in good health.
I don't really get behind the structure yet. Is it possible that you can share your demo content and your requirements? It doesn't matter that it's in Spanish. 
Best regards from Berlin

**Comment by pmoreno-rodriguez** [comment]
Hi @traumturbulenzen 

Here you have the demo content:
[https://github.com/pmoreno-rodriguez/grav-theme-future2021/tree/develop/_demo](https://github.com/pmoreno-rodriguez/grav-theme-future2021/tree/develop/_demo)
