### ISSUE TITLE
Missing |raw Twig filter in simplesearch_item.html.twig

### ISSUE THREAD

**Issue by Fazarel** [pmoreno-rodriguez/grav-theme-future2021#26]
In order to render images in search results, I had to modify in simplesearch_item.html.twig
```
{% if banner %}
    <div class="search-image">
        <a href="{{ page.url }}">{{ banner }}</a>
    </div>
```
into
```
{% if banner %}
    <div class="search-image">
        <a href="{{ page.url }}">{{ banner|raw }}</a>
    </div>
```

**Comment by pmoreno-rodriguez** [comment]
HI @Fazarel 

In simplesearch_item you already have this on banner ``` {% set banner = page.media[page.header.primaryImage].loading('lazy').html(page.title,page.title)|raw ?: page.media.images|first  %}``` with |raw filter.

What's wrong? Can you upload a screenshot with the issue?

**Comment by pmoreno-rodriguez** [comment]
Maybe you mean when the first image is taken by default?

**Comment by Fazarel** [comment]
Demo content, grav and theme up to date.

With `<a href="{{ page.url }}">{{ banner }}</a>`:
![Screenshot 2023-02-03 at 13-43-10 Search Results Grav](https://user-images.githubusercontent.com/35377747/216606967-cb04a1dd-cc9e-4afc-b611-34dc10156163.png)

With `<a href="{{ page.url }}">{{ banner|raw }}</a>`:
![Screenshot 2023-02-03 at 13-44-21 Search Results Grav](https://user-images.githubusercontent.com/35377747/216607045-36b43dd6-17de-4ce4-8edc-5919ffe53052.png)

**Comment by pmoreno-rodriguez** [comment]
Could you test the last [simplesearch_item.html.twig](https://github.com/pmoreno-rodriguez/grav-theme-future2021/blob/main/templates/partials/simplesearch_item.html.twig) from the main branch ?.

This file was modified in the last month for the next version of the theme.

**Comment by pmoreno-rodriguez** [comment]
Sorry, test it from the [develop branch](https://github.com/pmoreno-rodriguez/grav-theme-future2021/blob/develop/templates/partials/simplesearch_item.html.twig).

**Comment by pikim** [comment]
I've also made some modifications on that file as I experienced problems initially. See https://github.com/pmoreno-rodriguez/grav-theme-future2021/pull/25

Not this topic, but also concerns simplesearch_item.html.twig:
if `<p>{{ page.summary|truncate(200)|raw }}</p>` ends in a table the whole result layout gets messed up. Therefore I disabled the line on my page and don't show any content, but only the image and the header.

**Comment by pmoreno-rodriguez** [comment]
@pikim  could you upload a screenshot about this issue. I'd like to see it.

**Comment by Fazarel** [comment]
> Not this topic, but also concerns simplesearch_item.html.twig: if `<p>{{ page.summary|truncate(200)|raw }}</p>` ends in a table the whole result layout gets messed up. Therefore I disabled the line on my page and don't show any content, but only the image and the header.

Similar problem with `<p>{{ page.summary|truncate(200)|raw }}</p>`. If cut ends in a url, layout messed up. I removed `|truncate(200)` filter, so summary size is now controlled by /user/env/site.test/config/site.yaml. In this case, I don't know why, no problem if summary ends in a middle of a link (the word is cut but the link works and the layout is preserved).

**Comment by Fazarel** [comment]
> Sorry, test it from the [develop branch](https://github.com/pmoreno-rodriguez/grav-theme-future2021/blob/develop/templates/partials/simplesearch_item.html.twig).

Works with [simplesearch_item.html.twig](https://github.com/pmoreno-rodriguez/grav-theme-future2021/blob/develop/templates/partials/simplesearch_item.html.twig) from develop branch.

But `.cropZoom(100,100)` is redundant with [custom.css](https://github.com/pmoreno-rodriguez/grav-theme-future2021/blob/develop/assets/css/custom.css) (maybe [misc.css](https://github.com/pmoreno-rodriguez/grav-theme-future2021/pull/25) in the future):
```
/* Styles to support svg images in search results */

.search-row {
  display: flex;
  align-items: top;
  
}
.search-image img {
  overflow:hidden;
  width: 100px;
  height: 100px;
  object-fit: cover;
  object-position: 0 100%;
}
@media only all and (max-width: 47.938em) {
  .search-image img {display:none;} 
}
.search-item {
  margin-left: 30px;
  margin-bottom: 50px;
}
```

**Comment by pmoreno-rodriguez** [comment]
Yes. I know. I will remove width and height from CSS.

**Comment by pikim** [comment]
> @pikim could you upload a screenshot about this issue. I'd like to see it.

When I use your current develop branch it looks like

![image](https://user-images.githubusercontent.com/11775849/216788309-166a35de-0f05-4651-9ee5-bfa73494a854.png)

**Comment by pikim** [comment]
> @pikim could you upload a screenshot about this issue. I'd like to see it.

@pmoreno-rodriguez 
When I use your current develop branch (from 2 minutes ago) it looks like this:
![image](https://user-images.githubusercontent.com/11775849/216788397-16b23248-55a7-48fe-ba56-2c2da5ab1b43.png)

The image is too wide, there is no separation line between results and search results are cascaded due to corrupted tables.
