### ISSUE TITLE
Issues with login

### ISSUE THREAD

**Issue by pikim** [pmoreno-rodriguez/grav-theme-future2021#27]
When logged in and still on the login status site, it's not possible to open the menu. This is because
```
{% block menu %}
  {% include 'partials/sidebar_right.html.twig' %}
{% endblock %}
```
is missing in `partials/login-status.html.twig`.

On the other hand when you log out and goto the login site again, there is a message saying that you were successfully logged out.

**Comment by pmoreno-rodriguez** [comment]
The message is preset in the login plugin and, for now, I need more knowledge to be able to modify it. However, most Grav themes don't include as much customization and leave these kinds of enhancements to the developers.

I have added the login.html.twig file to the development branch with the menu block.

**Comment by pmoreno-rodriguez** [comment]
Try the [demo site](http://future.juanvillen.es/) (I have uploaded the new version 1.0.3 there).

**Comment by pikim** [comment]
> Try the [demo site](http://future.juanvillen.es/) (I have uploaded the new version 1.0.3 there).

I have a first finding documented in the #25 thread and will have a more extensive look tomorrow.

**Comment by pmoreno-rodriguez** [comment]
Fixed in develop branch for the next version.
