### ISSUE TITLE
Brilliant theme

### ISSUE THREAD

**Issue by SudoMakeCake** [pmoreno-rodriguez/grav-theme-future2021#3]
Hi

I really like your theme and I'm using it here - https://soundscapes.woollypigs.com/ 

Made a few edits to fit my needs. 

Though for the life of me I can't figure out how to get post into the Featured/minipost on the left handside on the front page. 

Any hints is much appreciated, thanks.

SMC

**Comment by SudoMakeCake** [comment]
Finally found it :)

in site.yaml add category to the taxonomies, like this: taxonomies: [tag, category, featured]

Thanks again.

**Comment by pmoreno-rodriguez** [comment]
Hi.
Sorry for waiting.
In category you have to write "minipost" to show that post in left sidebar. If you want to change this keyword, you can change the line 7 in partials/miniposts.html.twig and choose what you want.
In the future version of theme I will implement this function.

Thanks for use this theme. Enjoy it!
