### ISSUE TITLE
HTML/CSS bugs

### ISSUE THREAD

**Issue by Misha-N** [pmoreno-rodriguez/grav-theme-future2021#31]
Hello I found some bugs in HTML/CSS in new version.
In Blog page - share options are displayed as list and missing:
    border-left: solid 1px rgba(160, 160, 160, 0.3);
    display: inline-block;
    font-size: larger;
    font-weight: 400;
    margin: 0 0 0 1em;
    padding: 0 0 0 1em;
    text-transform: uppercase; 

also I was also not able to hide "image featured" in feature page block - it display one big image every time.

**Comment by pmoreno-rodriguez** [comment]
Hello @Misha-N 

I must have done something wrong in the last commit on Github, because you are right, there are new features that are not in version 1.0.4

I'll take a look to see what went wrong.
Thank you for your suggestion.

**Comment by pmoreno-rodriguez** [comment]
Hi @Misha-N 

I just downloaded version 1.0.4 from GitHub and regarding the social media icons on the blog posts I think they are ok as you can check on the demo page [Future 2021 Demo](http://future .juanvillen.es/blog).

Regarding the second question, I assume that you mean that blog articles show an image, even if you have an empty featured image. Is it so?

The code is made to fetch an image, if there are images in page.media. In the next version of Future2021, I will put as an option (toggleable) the power to activate the image of the blog article.

**Comment by pmoreno-rodriguez** [comment]
Could you try the option to disable the main image from the 'feature' branch. Is this what you suggest?

[https://github.com/pmoreno-rodriguez/grav-theme-future2021/tree/features](https://github.com/pmoreno-rodriguez/grav-theme-future2021/tree/features)

**Comment by Misha-N** [comment]
I tried it, I can see the toggle for the primary image, but it still doesn't work on the feature page. Maybe I'm doing something wrong, but on the demo page BIENVENIDO -> CARACTERÍSTICAS you have 3 blocks. For me it generates one big image above them (first - when i leave it blank or selected even if I toggle off primary image in features branch) - https://michal-fryba.eu/. The only thing I managed to do was to comment out the code in /grav/user/themes/future2021/templates/modular/

I also found that pagination is not showing in blog.

As for the sharing icons - they are now showing correctly - I don't know what it was, maybe some bad resolution of my monitor.

**Comment by pmoreno-rodriguez** [comment]
Okay.

I have already modified the templates features.html.twig and banner.html.twig (in the [features branch](https://github.com/pmoreno-rodriguez/grav-theme-future2021/tree/features/templates/modular)), which also included the primary image. I have not been able to detect this error before since I use images in SVG format and these are not loaded in the same way as other images. I will address this small bug in the next version.

On the other hand, to see the pagination in the Blog, you must take into account the number of items that you will show. By default, the theme is configured to display 5 post articles per page. If you do not have those 5 articles, the pagination buttons will not be activated (in your example page, you only have 4). This option is in the blog page settings, in the 'Blog Config' tab. By default pagination is enabled.

**Comment by Misha-N** [comment]
Thank you so much - I'll try using SVG format unril new version (also it would be nice if the images scaled to the same height - just a suggestion for future improvement) :)
However, on my website, the pagination on the blog doesn't show even when I have more than five articles. The first few articles don't show up (breadcrumbs also do not show). :/

**Comment by Misha-N** [comment]
I have this setting and i have 6 testing articles: 
title: 'CyberSecurity Blog'
author: 'Michal Frýba'
content:
    items:
        - '@self.children'
    limit: 5
    order:
        by: date
        dir: desc
    url_taxonomy_filters: true
shareicons:
    facebook: true
    twitter: true
    whatsapp: true
    telegram: true
show_sidebar: true
show_breadcrumbs: true
show_pagination: true

**Comment by pmoreno-rodriguez** [comment]
Hi @Misha-N.

I've pushed some changes to the feature branch. I think the problem with the pagination was in the blog.yaml, with the `header.content.pagination` option, which was not set.

Could you try it now?
I also pushed other changes to the feature branch, to tweak the main image enable/disable option and other little things.

**Comment by pmoreno-rodriguez** [comment]
Fixed in develop branch
