### ISSUE TITLE
No Sidebar with demo files.

### ISSUE THREAD

**Issue by XENNOK** [pmoreno-rodriguez/grav-theme-future2021#38]
![future](https://user-images.githubusercontent.com/38142171/236049623-c169d45f-e44b-4c69-8f2e-ca33d2896704.gif)

I am not sure why I dont have the left sidebar at all. It all seems off without it.
I just installed the theme over grav theme installer, than deployed _demo/pages into pages and _demo/config into config.

I am new to grav but checked it several times and checked with other themes but I cant get this one to work.

**Comment by pmoreno-rodriguez** [comment]
Hi @XENNOK 

Have you enabled Show sidebar on pages? This variable is set to enable or disable the left sidebar per page. It is not a global variable, so it must be enabled on each page. By default it is disabled.

![show_sidebar_future](https://user-images.githubusercontent.com/60596353/236401069-cc527bc4-9cba-42e5-8fd8-ad1b67fc7f85.jpg)

**Comment by XENNOK** [comment]
And now I feel stupid. :/
You are right, after that the site works. ;)

**Comment by raymondjohnson** [comment]
Don't feel stupid, @XENNOK! I've been trying to figure this one out for a while since the sidebar used to show but then disappeared. I also tried starting from scratch with the demo site, and when it didn't work there, I figured I'd better look to see if anyone left a useful bug report.

**Comment by pmoreno-rodriguez** [comment]
@XENNOK, I'll update the demo pages shortly, as they don't have the option to show the sidebar.
But with a blank site and the latest version of the theme it should work.

**Comment by pmoreno-rodriguez** [comment]
Solved in new version 1.0.6
