### ISSUE TITLE
Suggestion: serve google fonts locally

### ISSUE THREAD

**Issue by Fazarel** [pmoreno-rodriguez/grav-theme-future2021#46]
Would it be possible to add an option to use locally hosted google fonts? As you did for another theme [grav-theme-editorial:  Serve google fonts locally #19 ](https://github.com/pmoreno-rodriguez/grav-theme-editorial/pull/19)
To make future2021 GDPR compliant and satisfy users who want to preserve their privacy.
Many thanks to you !

**Comment by pmoreno-rodriguez** [comment]
Added in 1.2.2
