### ISSUE TITLE
How to properly delete the right toolbar ?

### ISSUE THREAD

**Issue by Oxyaxion** [pmoreno-rodriguez/grav-theme-future2021#47]
Hello,

I'm trying to remove the menu on the right especially the login form from the template.

I didn't figure it out how to do this properly without deeply changing the core / theme.

The option `menu_login: false` doesn't work.

Do you have a proper solution ?

Thanks.

![Screenshot_20230830_112405](https://github.com/pmoreno-rodriguez/grav-theme-future2021/assets/36089699/d3e6febf-7a5a-4f4f-9ed9-8842acf49b2e)

![Screenshot_20230830_1124108](https://github.com/pmoreno-rodriguez/grav-theme-future2021/assets/36089699/e15e4539-ddf2-47f4-961c-33080df12552)

Snippet from : 

`user/config/themes/future2021.yaml`

![Screenshot_20230830_112533](https://github.com/pmoreno-rodriguez/grav-theme-future2021/assets/36089699/2083941e-d781-4688-b7a7-f52344c97d2f)

**Comment by pmoreno-rodriguez** [comment]
Hello.

The right menu not only shows information related to blog pages (taxonomies, archives, feeds, etc, only if the corresponding plugins are activated), but also shows the top menu when browsing on mobile devices.

I wonder why you would want to remove that menu on the right. However, this involves a deep remodeling of the code, which, at the moment, is not in my plans.

If you do some digging into the code you can see that that menu loads in the `{% block menu %}` block in different twig templates. You can play commenting on those blocks to see if the result is what you are looking for.

On the other hand, `menu_login` is not to show or hide the menu icon on the right, but to show an icon in the top bar in case you want to enable multi-user access for private pages available in Grav.

**Comment by Oxyaxion** [comment]
Hello,

Thanks for the feedback. Indeed I did some test from a smartphone + taxonomies plugins, I see what your mean

In fact my goal is not to remove the menu the menu. But just to hide the login button to my visitors.
Editors will be able to login in by the grav / admin panel, thus I want to maximize security and avoid login attempts as much as possible.

Especially as I don't understand what this button is really for. Knowing that once connected it doesn't allow you to edit pages.

**Comment by pmoreno-rodriguez** [comment]
The login that is done through the Login button is to access private pages previously defined as such in the security tab of each page. [https://learn.getgrav.org/17/admin-panel/page/security](https://learn.getgrav.org/17/admin-panel/page/security) 
To prevent a user from accessing the administration panel you just have to disable the Admin plugin. But that would prevent you from also accessing and having to do all the work of managing pages directly in the .md files of each page in your folders.

To have an address to the admin panel other than /admin you should set an alternative route in the admin.yaml file (in the /user/config/plugins folder) by changing `route: /your_custom_route`

**Comment by Oxyaxion** [comment]
Hello,

Workarround was super easy , to remove the "login button" from the right bar 

in `templates\partials\sidebar_right.html.twig`

Comment from line 61 -> 73.

**Comment by pmoreno-rodriguez** [comment]
Hello.

I see that in the end you have been able to adapt the theme to your needs. At first I thought you wanted to remove the menu button from the right sidebar, but it was a mix-up from the screenshots you showed.

Well, if everything goes well, can we close this issue?
