### ISSUE TITLE
Cannot show any entry inside the "Featured" section

### ISSUE THREAD

**Issue by corum** [pmoreno-rodriguez/grav-theme-future2021#48]
Hello, maybe this is a dumb question but I cannot manage to show anything inside the left sidebar "Featured" section.
I've read the docs and couldn't end up with anything useful.
The Theme settings tips are a little misleading to me.
Can you please specify how to get that feature working?
Thanks and congratulations for the awesome job in developing this gorgeous theme.

**Comment by pmoreno-rodriguez** [comment]
Hello @corum. First of all, I want to thank you for using the Future2021 theme.

To display blog posts in the Featured section, you must define the taxonomy tag in the Blog section, in the theme settings. It is true that here it appears as "Miniposts category" (something I will have to change in future versions).

![minipost_config](https://github.com/pmoreno-rodriguez/grav-theme-future2021/assets/60596353/20918bb1-2a38-40c9-a0b6-db025f5e67a5)

Imagine that here you define the text "featured", then on each blog article page (item type), in the "Options-->Category" tab, you must write the text "featured" (in our example), and so on. will show the articles of this category in the left sidebar.

![minipost_tag](https://github.com/pmoreno-rodriguez/grav-theme-future2021/assets/60596353/30043996-133f-4eff-adb5-180429cc2698)

I will add updating the documentation to do this to my to-do list.

**Comment by corum** [comment]
Hello @pmoreno-rodriguez and many thanks for your prompt reply.
I followed your directions and in my page have:
![immagine](https://github.com/pmoreno-rodriguez/grav-theme-future2021/assets/1676674/e70aae77-398e-4353-8ae3-1423898df5b8)
In my site config I have:
![immagine](https://github.com/pmoreno-rodriguez/grav-theme-future2021/assets/1676674/ea2b61e2-fd4b-4492-aa24-119c7724a806)
In the website page i got:
![immagine](https://github.com/pmoreno-rodriguez/grav-theme-future2021/assets/1676674/058b424b-15e0-4a00-83e0-52626e637030)

Just in doubt I pick the wrong template. My page named "mini" is configured like this:
![immagine](https://github.com/pmoreno-rodriguez/grav-theme-future2021/assets/1676674/9d2b92d4-77ef-43d7-8741-28c0bd8b4a0d)
And, of course, my template page is like this:
![immagine](https://github.com/pmoreno-rodriguez/grav-theme-future2021/assets/1676674/de9294ce-78de-4e13-a85b-50e0d01b560f)

I'm pretty sure I'm doing something wrong. But what? :-)
Thanks for your patience.

**Comment by corum** [comment]
Well, I made a fresh install of the latest Grav+Admin bundle, re-created admin user, re-uploaded your Theme demo and BUM!
Everything is working as expected.
I apologize for the time you wasted for me. :)
Thanks!

**Comment by pmoreno-rodriguez** [comment]
Sometimes with demo pages you can learn a lot about how a theme works in Grav.
Enjoy the theme and feel free to report any problems
