### ISSUE TITLE
Installation results in an error

### ISSUE THREAD

**Issue by dcrobertson01** [pmoreno-rodriguez/grav-theme-future2021#5]
Tried to install theme via bin/gpm install future2021

Got the following error
/home/robertso/moko-papa.nz/grav/user/themes/future2021/templates/partials/taxonomylist.html.twig

{% set taxlist = children_only is defined ? taxonomylist.getChildPagesTags() : taxonomylist.get() %}
 
{% if taxlist %}
  <ul class="menulink">
    <li>
        {% for tax,value in taxlist[taxonomy]|sort %}
            {% set active = uri.param(taxonomy) == tax? 'active' : '' %}
            <a class="tags {{ active }}" href="{{ base_url }}/{{ taxonomy }}{{ config.system.param_sep }}{{ tax }}">{{ tax }}</a>
        {% endfor %}
    </li>
  </ul>
{% endif %}

Arguments

    "The sort filter only works with arrays or "Traversable", got "NULL"."

I have not had a lot of time to look into it - tried commenting out the template, but no luck. Might be able to look on a better machine later.

**Comment by RomainCos** [comment]
I have the same error in the installation process.
In the Admin Panel : **Page->options->Taxinomies, set a Tag** (whatever)
Or in the folder  : **grav/user/pages/01.homr/defaut.md** complete with :
 >taxonomy:
 >       category:
>             - _**whatever cat**_
>        tag:
>              - _**whatever tag**_

**Comment by pmoreno-rodriguez** [comment]
Hi @dcrobertson01 and @RomainCos 

Can you try to download the new _demo folder from develop branch?. In older _demo folder, the markdown files were saved with .es prefix. I think that is the cause why the taxonomies don't work.

**Comment by jochen-koegel** [comment]
Hi @pmoreno-rodriguez , 
the error is a result of the missing taxonomy entry in the modular child pages. 
We used version 1.0.1 without any taxonomy entry. After the update to 1.0.2 the taxonomy is required. 
Adding an exemplary  
taxonomy:
    category:
        - About
    tag:
        - tag2
    author:
        - 'Juan Villén'

from the _demo folder to the modular child  pages solved the problem.

**Comment by pmoreno-rodriguez** [comment]
Hi @jochen-koegel 
In the next version I'll set the author tag as a default tag
