### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by diomed** [pmoreno-rodriguez/grav-theme-future2021#50]
hello

not an issue, but suggestion

could you maybe make main container to have option to be set narrower?
like to have option for us to choose width of it. or you know just have some size modifiers

![2023-11-05 08 38 05 getuikit com 9a16077ece5a](https://github.com/pmoreno-rodriguez/grav-theme-future2021/assets/72777/d81a5a68-b140-42ca-acd8-67e26fba187a)

 *image is for illustrative purposes

**Comment by pmoreno-rodriguez** [comment]
The original HTML5Up theme is not made to use different configurations of the main container, but rather works with percentage width for the sidebar and main section.

I have already implemented the option to enable and disable the sidebar on the pages, individually, and making a modification like the one you suggest involves making profound changes to the page styles, and it is not among my plans to do this, at the moment.

**Comment by diomed** [comment]
allright then
