### ISSUE TITLE
Logo in image format to be implemented in the header

### ISSUE THREAD

**Issue by ghost** [pmoreno-rodriguez/grav-theme-future2021#52]
Hi Pedro,

One nice nice-to-have improvement for the Future2021 template would be for users to be able to add a custom .jpg/.png version of a logo in the header of the website. See below where exactly I am referring to:
![image](https://github.com/pmoreno-rodriguez/grav-theme-future2021/assets/115343648/aff81076-fd83-455a-b462-d1fe57a3c94c)

The idea is that logo image maintains the same clickable properties as the text currently does.

Thanks a lot

**Comment by pmoreno-rodriguez** [comment]
Hi @piccolopi 

Can yo test the latest version of theme?

**Comment by pmoreno-rodriguez** [comment]
Fixed in V 1.2.4
