### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by motionthings** [pmoreno-rodriguez/grav-theme-future2021#53]
Not a big deal. But, the demo site link in the admin panel of grav should probably be changed or redirected?
Feel free to close this ticket anytime you feel like it.
Have a wonderful day :)

![image](https://github.com/pmoreno-rodriguez/grav-theme-future2021/assets/264911/8f69ec5e-8433-4c76-8a9c-68a9403cef4f)

**Comment by pmoreno-rodriguez** [comment]
@motionthings thanks for your suggestion. I'll fix it in the next version.

**Comment by pmoreno-rodriguez** [comment]
Solved in 1.2.5 version.
