### ISSUE TITLE
Shortcodes seems does not work

### ISSUE THREAD

**Issue by onavascuez** [pmoreno-rodriguez/grav-theme-future2021#59]
I am setting up a new website using this template.
For now it looks fantastic. Lot of features, well designed,...

But I was trying to put some content using the shortcodes, but it seems that this feature does not running well. At least for me.
Example:
~~[Temporary link](#) meanwhile I try to fix it.~~

As you can see, I directly copied the content from [here](https://raw.githubusercontent.com/pmoreno-rodriguez/grav-theme-future2021/refs/heads/develop/_demo/pages/08.shortcodes/default.md) to be sure that I am not forgetting something, but no... it seems not working for me.

Maybe I need to activate or put something in config files to activate it? Or use some plugin?
I am going to investigate what happen...

If its useful, I am using php 8.3

Thank you so much!

**Comment by onavascuez** [comment]
Ok, fixed, maybe is commented in some place, I think not. 

We need the **Shortcode Core** plugin to enable this feature. 

I was looking for the different official plugins, and seeing the code from this one it seems going to work..., and yes, it works!

**Comment by pmoreno-rodriguez** [comment]
The theme is prepared for the included shortcodes, but to be able to use any shortcode of any theme or plugin, it is always necessary to install the Shortcode Core plugin, although I do not have it as a dependency on the theme.
