### ISSUE TITLE
Breadcrumb links underlining too long

### ISSUE THREAD

**Issue by pikim** [pmoreno-rodriguez/grav-theme-future2021#8]
When breadcrumbs are active, their links are underlined until the separator and not only the text, see

![Screenshot_20221221_094901](https://user-images.githubusercontent.com/11775849/208861233-4e5086cd-1db0-463d-9107-9992351dfa73.png)

**Comment by pmoreno-rodriguez** [comment]
I'll take a look for the next version.

**Comment by pmoreno-rodriguez** [comment]
Fixed on [develop branch.](https://github.com/pmoreno-rodriguez/grav-theme-future2021/blob/develop/assets/css/misc.css)
